include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  
  plugins:
    - custom_lint
  
linter:
  rules:
    prefer_double_quotes: true
    unawaited_futures: true
    unnecessary_late: true
    no_leading_underscores_for_local_identifiers: true
    prefer_const_constructors: true
    file_names: true
    avoid_print: true
    prefer_final_locals: true
    no_logic_in_create_state: true
    close_sinks: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    curly_braces_in_flow_control_structures: true
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    prefer_const_constructors_in_immutables: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_if_elements_to_conditional_expressions: true
    require_trailing_commas: true