// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRV4i9NJC4A2i5yXlnGitSHAKrH1mDHkc',
    appId: '1:181457111638:web:9152cb043ec86b0393c9f7',
    messagingSenderId: '181457111638',
    projectId: 'flix-id-995e5',
    authDomain: 'flix-id-995e5.firebaseapp.com',
    storageBucket: 'flix-id-995e5.firebasestorage.app',
    measurementId: 'G-5ZSF2TM9QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWuEJL2dAZjGcpsunk1oxzQ1Pt_bsMqTs',
    appId: '1:181457111638:android:331e5733ccf99fc293c9f7',
    messagingSenderId: '181457111638',
    projectId: 'flix-id-995e5',
    storageBucket: 'flix-id-995e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgNrpLprGLBn-ts836nXYOQhfFT_5eUIg',
    appId: '1:181457111638:ios:e2fb4aae90bbb33693c9f7',
    messagingSenderId: '181457111638',
    projectId: 'flix-id-995e5',
    storageBucket: 'flix-id-995e5.firebasestorage.app',
    iosBundleId: 'com.example.flixId',
  );
}
